package:
  name: ccpi-plugins
  version: {{ environ['CIL_VERSION'] }}


build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
test:
  requires:
    - python-wget
    - cvxpy # [ unix and py36 and np115 ]

  source_files:
    - ./test # [win]
    - ./ccpi/Wrappers/Python/test # [not win] 

  commands:
    - python -c "import os; print (os.getcwd())"
    - python -m unittest discover # [win]
    - python -m unittest discover -s ccpi/Wrappers/Python/test # [not win]
    
requirements:
  build:
    - python
    - setuptools
    - numpy {{ numpy }}

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - ccpi-framework >=20.09
    - ccpi-reconstruction >=20.09
    - ccpi-regulariser >=20.09
    - matplotlib
	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache 2.0 License
  summary: 'CCPi Framework Plugins'
